version: "2"

services:
  nginx:
    image: umputun/nginx-le:latest
    container_name: nginx
    hostname: nginx
    restart: always

    logging: &default_logging
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - ./etc/ssl:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./services.conf:/etc/nginx/service.conf
      - ./hugo/public:/var/www
      - ./var/stats:/var/stats
      - ./var/media/:/var/media
    ports:
      - "80:80"
      - "443:443"

    environment:
      - TZ=America/Chicago
      - LETSENCRYPT=true
      - LE_EMAIL=umputun@gmail.com
      - LE_FQDN=podcast.umputun.com,remark42.umputun.com

    depends_on:
      - remark42
      - stats

  remark42:
    image: umputun/remark42:master
    container_name: "remark42"
    hostname: "remark42"
    restart: always
    logging: *default_logging

    environment:
      - MHOST
      - USER=umputun
      - SECRET=$REMARK_SECRET
      - REMARK_URL=https://remark42.umputun.com
      - SITE=uwp
      - ADMIN_SHARED_ID=github_ef0f706a79cc24b17bbbb374cd234a691d034128
      - ADMIN_SHARED_EMAIL=remark42@umputun.com
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - IMG_PROXY=true
      - AVATAR_RESIZE=48
      - LOW_SCORE=-10
      - CRITICAL_SCORE=-15
      - CACHE_MAX_SIZE=50000000
      - CACHE_MAX_VALUE=200000
      - CACHE_MAX_ITEMS=1000
      - NOTIFY_TYPE=telegram
      - NOTIFY_TELEGRAM_CHAN=uwp_comments
      - NOTIFY_TELEGRAM_TOKEN
      - MAX_COMMENT_SIZE=2000
      - ADMIN_PASSWD=$REMARK_ADMIN_PASSWD
      - READONLY_AGE=120
      - AUTH_EMAIL_ENABLE=true
      - AUTH_EMAIL_HOST=mail-server
      - AUTH_EMAIL_PORT=25
      - AUTH_TWITTER_CID
      - AUTH_TWITTER_CSEC
      - AUTH_GITHUB_CID
      - AUTH_GITHUB_CSEC
      - AUTH_GOOGLE_CID
      - AUTH_GOOGLE_CSEC
      - AUTH_YANDEX_CID
      - AUTH_YANDEX_CSEC
      - AUTH_FACEBOOK_CID
      - AUTH_FACEBOOK_CSEC
      - AUTH_EMAIL_USER=remark42@mg.umputun.com
      - AUTH_EMAIL_FROM=confirmation@umputun.com
      - AUTH_EMAIL_PASSWD
    volumes:
      - ./var/remark42:/srv/var

  stats:
    build: stats
    hostname: stats
    container_name: stats
    restart: always
    logging: *default_logging
    network_mode: host
    volumes:
      - ./var/stats:/stats
      - ./var/vnstat:/var/lib/vnstat

  updater:
    build: updater
    hostname: updater
    container_name: updater
    restart: always
    logging: *default_logging
    volumes:
      - /home/umputun/.ssh/id_rsa.pub:/home/app/.ssh/id_rsa.pub
      - /home/umputun/.ssh/id_rsa:/home/app/.ssh/id_rsa

#  rss2twitter:
#    image: umputun/rss2twitter:master
#    container_name: "rss2twitter"
#    hostname: "rss2twitter"
#    restart: always
#    logging: *default_logging
#
#    environment:
#      - REFRESH=2m
#      - FEED=http://feeds.rucast.net/Umputun
#      - TWI_CONSUMER_KEY
#      - TWI_CONSUMER_SECRET
#      - TWI_ACCESS_TOKEN
#      - TWI_ACCESS_SECRET

  feed-master:
    image: umputun/feed-master:master
    container_name: "feed-master"
    hostname: "feed-master"
    restart: always
    logging: *default_logging

    environment:
      - DEBUG=false
      - FM_DB=/srv/var/feed-master.bdb
      - FM_FEED=http://feeds.rucast.net/Umputun
      - TELEGRAM_CHAN=uwp_podcast
      - TELEGRAM_TOKEN
      - TWI_CONSUMER_KEY
      - TWI_CONSUMER_SECRET
      - TWI_ACCESS_TOKEN
      - TWI_ACCESS_SECRET
    volumes:
      - ./var:/srv/var

  monit:
    build: monit
    hostname: monit
    container_name: monit
    restart: always
    logging: *default_logging
    ports:
      - "9009:9009"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mail-server:
    image: stevenolen/mailgun-smtp-server
    container_name: mail-server
    restart: always
    logging: *default_logging
    environment:
      - MG_KEY
      - MG_DOMAIN=mg.umputun.com
